### ISSUE TITLE
Powerpoint / PDF version of talk

### ISSUE THREAD

**Issue by reidca** [bobthemighty/talk-boundaries#1]
Saw your talk yesterday at comsum and wanted to share the slides within our team, was wondering whether you have a version of the slides that can be easily shared?

**Comment by bobthemighty** [comment]
I'll stick it up on the blog so that you can access it through a webpage instead of running it locally - would that work?

**Comment by reidca** [comment]
that would be great, and thank you once again for the talk. For me it was the standout talk of what was an excellent conference.

**Comment by bobthemighty** [comment]
Here you go - here's a first, terrible, effort at presenting online. I'll try to clean it up when I've got a bit more time :)

https://bobthemighty.github.io/talk-boundaries/ Let me know if that answers your requirements, and I'll close the issue.

**Comment by reidca** [comment]
amazing, thank you for doing this so quickly!
